/* marlin: auto-generated weak stubs */
#include <linux/linkage.h>
#include <linux/types.h>
__attribute__((weak)) long __cgroup_bpf_attach(void) { return 0; }
__attribute__((weak)) long __cgroup_bpf_detach(void) { return 0; }
__attribute__((weak)) long __cgroup_bpf_query(void) { return 0; }
__attribute__((weak)) long __cgroup_bpf_run_filter_getsockopt(void) { return 0; }
__attribute__((weak)) long __cgroup_bpf_run_filter_setsockopt(void) { return 0; }
__attribute__((weak)) long __clk_post_reparent(void) { return 0; }
__attribute__((weak)) long __clk_pre_reparent(void) { return 0; }
__attribute__((weak)) long __dev_flush(void) { return 0; }
__attribute__((weak)) long __dev_map_hash_lookup_elem(void) { return 0; }
__attribute__((weak)) long __dev_map_lookup_elem(void) { return 0; }
__attribute__((weak)) long __inet_bind(void) { return 0; }
__attribute__((weak)) long __xdp_release_frame(void) { return 0; }
__attribute__((weak)) long audio_aio_async_write_ack(void) { return -1; }
__attribute__((weak)) long audio_aio_enable(void) { return -1; }
__attribute__((weak)) long audio_aio_fsync(void) { return -1; }
__attribute__((weak)) long audio_aio_open(void) { return -1; }
__attribute__((weak)) long audio_aio_post_event(void) { return -1; }
__attribute__((weak)) long audio_aio_release(void) { return -1; }
__attribute__((weak)) long bpf_ctx_narrow_access_offset(void) { return 0; }
__attribute__((weak)) long bpf_extension_prog_ops(void) { return 0; }
__attribute__((weak)) long bpf_extension_verifier_ops(void) { return 0; }
__attribute__((weak)) long bpf_image_ksym_add(void) { return 0; }
__attribute__((weak)) long bpf_iter_get_info(void) { return 0; }
__attribute__((weak)) long bpf_iter_link_attach(void) { return 0; }
__attribute__((weak)) long bpf_iter_new_fd(void) { return 0; }
__attribute__((weak)) long bpf_iter_prog_supported(void) { return 0; }
__attribute__((weak)) long bpf_iter_run_prog(void) { return 0; }
__attribute__((weak)) long bpf_jit_alloc_exec_page(void) { return 0; }
__attribute__((weak)) long bpf_ringbuf_discard_proto(void) { return 0; }
__attribute__((weak)) long bpf_ringbuf_output_proto(void) { return 0; }
__attribute__((weak)) long bpf_ringbuf_query_proto(void) { return 0; }
__attribute__((weak)) long bpf_ringbuf_reserve_proto(void) { return 0; }
__attribute__((weak)) long bpf_ringbuf_submit_proto(void) { return 0; }
__attribute__((weak)) long bpf_snprintf_btf_proto(void) { return 0; }
__attribute__((weak)) long bpf_struct_ops_map_ops(void) { return 0; }
__attribute__((weak)) long bpf_struct_ops_prog_ops(void) { return 0; }
__attribute__((weak)) long bpf_struct_ops_verifier_ops(void) { return 0; }
__attribute__((weak)) long bpf_trampoline_link_prog(void) { return 0; }
__attribute__((weak)) long bpf_trampoline_lookup(void) { return 0; }
__attribute__((weak)) long bpf_trampoline_put(void) { return 0; }
__attribute__((weak)) long bpf_trampoline_unlink_prog(void) { return 0; }
__attribute__((weak)) long btf_resolve_helper_id(void) { return 0; }
__attribute__((weak)) long btfm_slim_hw_init(void) { return -1; }
__attribute__((weak)) long cfg80211_vendor_cmd_reply(void) { return 0; }
__attribute__((weak)) long cg_dev_prog_ops(void) { return 0; }
__attribute__((weak)) long cg_dev_verifier_ops(void) { return 0; }
__attribute__((weak)) long cg_sockopt_prog_ops(void) { return 0; }
__attribute__((weak)) long cg_sockopt_verifier_ops(void) { return 0; }
__attribute__((weak)) long cg_sysctl_prog_ops(void) { return 0; }
__attribute__((weak)) long cg_sysctl_verifier_ops(void) { return 0; }
__attribute__((weak)) long cgroup_bpf_get(void) { return 0; }
__attribute__((weak)) long cgroup_bpf_inherit(void) { return 0; }
__attribute__((weak)) long cgroup_bpf_offline(void) { return 0; }
__attribute__((weak)) long cgroup_bpf_prog_attach(void) { return 0; }
__attribute__((weak)) long cgroup_bpf_prog_detach(void) { return 0; }
__attribute__((weak)) long cgroup_bpf_prog_query(void) { return 0; }
__attribute__((weak)) long dev_map_enqueue(void) { return 0; }
__attribute__((weak)) long dev_map_generic_redirect(void) { return 0; }
__attribute__((weak)) long dev_map_hash_ops(void) { return 0; }
__attribute__((weak)) long dev_map_ops(void) { return 0; }
__attribute__((weak)) long dev_xdp_enqueue(void) { return 0; }
__attribute__((weak)) long dwc3_pd_vbus_ctrl(void) { return 0; }
__attribute__((weak)) long enable_volume_ramp(void) { return 0; }
__attribute__((weak)) long fdt_check_header(void) { return 0; }
__attribute__((weak)) long fdt_first_property_offset(void) { return 0; }
__attribute__((weak)) long fdt_get_mem_rsv(void) { return 0; }
__attribute__((weak)) long fdt_get_name(void) { return 0; }
__attribute__((weak)) long fdt_getprop(void) { return 0; }
__attribute__((weak)) long fdt_getprop_by_offset(void) { return 0; }
__attribute__((weak)) long fdt_next_node(void) { return 0; }
__attribute__((weak)) long fdt_next_property_offset(void) { return 0; }
__attribute__((weak)) long fdt_node_check_compatible(void) { return 0; }
__attribute__((weak)) long fdt_parent_offset(void) { return 0; }
__attribute__((weak)) long fdt_path_offset(void) { return 0; }
__attribute__((weak)) long fdt_path_offset_namelen(void) { return 0; }
__attribute__((weak)) long fdt_setprop(void) { return 0; }
__attribute__((weak)) long find_vdd_level(void) { return 0; }
__attribute__((weak)) long flex_array_alloc(void) { return 0; }
__attribute__((weak)) long flex_array_free(void) { return 0; }
__attribute__((weak)) long flex_array_get(void) { return 0; }
__attribute__((weak)) long flex_array_get_ptr(void) { return 0; }
__attribute__((weak)) long flex_array_prealloc(void) { return 0; }
__attribute__((weak)) long flex_array_put(void) { return 0; }
__attribute__((weak)) long gcd(void) { return 0; }
__attribute__((weak)) long half_md4_transform(void) { return 0; }
__attribute__((weak)) long insert_eos_buf(void) { return 0; }
__attribute__((weak)) long int_sqrt(void) { return 0; }
__attribute__((weak)) long is_rate_valid(void) { return 0; }
__attribute__((weak)) long kgsl_add_event(void) { return -1; }
__attribute__((weak)) long kgsl_add_event_group(void) { return -1; }
__attribute__((weak)) long kgsl_add_fence_event(void) { return -1; }
__attribute__((weak)) long kgsl_cancel_events(void) { return -1; }
__attribute__((weak)) long kgsl_cancel_events_timestamp(void) { return -1; }
__attribute__((weak)) long kgsl_del_event_group(void) { return -1; }
__attribute__((weak)) long kgsl_drawobj_cmd_add_cmdlist(void) { return -1; }
__attribute__((weak)) long kgsl_drawobj_cmd_add_ibdesc(void) { return -1; }
__attribute__((weak)) long kgsl_drawobj_cmd_add_ibdesc_list(void) { return -1; }
__attribute__((weak)) long kgsl_drawobj_cmd_add_memlist(void) { return -1; }
__attribute__((weak)) long kgsl_drawobj_cmd_create(void) { return -1; }
__attribute__((weak)) long kgsl_drawobj_destroy(void) { return -1; }
__attribute__((weak)) long kgsl_drawobj_sparse_add_sparselist(void) { return -1; }
__attribute__((weak)) long kgsl_drawobj_sparse_create(void) { return -1; }
__attribute__((weak)) long kgsl_drawobj_sync_add_synclist(void) { return -1; }
__attribute__((weak)) long kgsl_drawobj_sync_add_syncpoints(void) { return -1; }
__attribute__((weak)) long kgsl_drawobj_sync_create(void) { return -1; }
__attribute__((weak)) long kgsl_drawobjs_cache_exit(void) { return -1; }
__attribute__((weak)) long kgsl_drawobjs_cache_init(void) { return -1; }
__attribute__((weak)) long kgsl_dump_syncpoints(void) { return -1; }
__attribute__((weak)) long kgsl_event_pending(void) { return -1; }
__attribute__((weak)) long kgsl_events_exit(void) { return -1; }
__attribute__((weak)) long kgsl_events_init(void) { return -1; }
__attribute__((weak)) long kgsl_flush_event_group(void) { return -1; }
__attribute__((weak)) long kgsl_ioctl_syncsource_create(void) { return -1; }
__attribute__((weak)) long kgsl_ioctl_syncsource_create_fence(void) { return -1; }
__attribute__((weak)) long kgsl_ioctl_syncsource_destroy(void) { return -1; }
__attribute__((weak)) long kgsl_ioctl_syncsource_signal_fence(void) { return -1; }
__attribute__((weak)) long kgsl_process_event_group(void) { return -1; }
__attribute__((weak)) long kgsl_process_event_groups(void) { return -1; }
__attribute__((weak)) long kgsl_sync_fence_async_wait(void) { return -1; }
__attribute__((weak)) long kgsl_sync_timeline_create(void) { return -1; }
__attribute__((weak)) long kgsl_sync_timeline_destroy(void) { return -1; }
__attribute__((weak)) long kgsl_syncsource_put(void) { return -1; }
__attribute__((weak)) long lcm_not_zero(void) { return 0; }
__attribute__((weak)) long md5_transform(void) { return 0; }
__attribute__((weak)) long mdss_dsi_debug_bus_init(void) { return 0; }
__attribute__((weak)) long mdss_dump_misr_data(void) { return 0; }
__attribute__((weak)) long mdss_mdp_hw_rev_debug_caps_init(void) { return 0; }
__attribute__((weak)) long module_add_driver(void) { return 0; }
__attribute__((weak)) long module_remove_driver(void) { return 0; }
__attribute__((weak)) long msm_ep_unconfig(void) { return 0; }
__attribute__((weak)) long msm_rpm_enter_sleep(void) { return 0; }
__attribute__((weak)) long msm_rpm_exit_sleep(void) { return 0; }
__attribute__((weak)) long msm_rpm_waiting_for_ack(void) { return 0; }
__attribute__((weak)) long net_rand_noise(void) { return 0; }
__attribute__((weak)) long of_msm_clock_register(void) { return 0; }
__attribute__((weak)) long parent_to_src_sel(void) { return 0; }
__attribute__((weak)) long q6asm_get_buf_index_from_token(void) { return 0; }
__attribute__((weak)) long q6asm_get_stream_id_from_token(void) { return 0; }
__attribute__((weak)) long q6asm_get_svc_version(void) { return 0; }
__attribute__((weak)) long rational_best_approximation(void) { return 0; }
__attribute__((weak)) long reciprocal_value(void) { return 0; }
__attribute__((weak)) long ringbuf_map_ops(void) { return 0; }
__attribute__((weak)) long swiotlb_alloc_coherent(void) { return 0; }
__attribute__((weak)) long swiotlb_dma_mapping_error(void) { return 0; }
__attribute__((weak)) long swiotlb_dma_supported(void) { return 0; }
__attribute__((weak)) long swiotlb_free_coherent(void) { return 0; }
__attribute__((weak)) long swiotlb_init(void) { return 0; }
__attribute__((weak)) long swiotlb_map_page(void) { return 0; }
__attribute__((weak)) long swiotlb_map_sg_attrs(void) { return 0; }
__attribute__((weak)) long swiotlb_sync_sg_for_cpu(void) { return 0; }
__attribute__((weak)) long swiotlb_sync_sg_for_device(void) { return 0; }
__attribute__((weak)) long swiotlb_sync_single_for_cpu(void) { return 0; }
__attribute__((weak)) long swiotlb_sync_single_for_device(void) { return 0; }
__attribute__((weak)) long swiotlb_unmap_page(void) { return 0; }
__attribute__((weak)) long swiotlb_unmap_sg_attrs(void) { return 0; }
__attribute__((weak)) long xdp_convert_zc_to_xdp_frame(void) { return 0; }
__attribute__((weak)) long xdp_warn(void) { return 0; }
