/* marlin: auto-generated weak stubs */
#include <linux/linkage.h>
#include <linux/types.h>
__attribute__((weak)) long __cgroup_bpf_attach() { return 0; }
__attribute__((weak)) long __cgroup_bpf_detach() { return 0; }
__attribute__((weak)) long __cgroup_bpf_query() { return 0; }
__attribute__((weak)) long __cgroup_bpf_run_filter_getsockopt() { return 0; }
__attribute__((weak)) long __cgroup_bpf_run_filter_setsockopt() { return 0; }
__attribute__((weak)) long __clk_post_reparent() { return 0; }
__attribute__((weak)) long __clk_pre_reparent() { return 0; }
__attribute__((weak)) long __dev_flush() { return 0; }
__attribute__((weak)) long __dev_map_hash_lookup_elem() { return 0; }
__attribute__((weak)) long __dev_map_lookup_elem() { return 0; }
__attribute__((weak)) long __inet_bind() { return 0; }
__attribute__((weak)) long __xdp_release_frame() { return 0; }
__attribute__((weak)) long audio_aio_async_write_ack() { return -1; }
__attribute__((weak)) long audio_aio_enable() { return -1; }
__attribute__((weak)) long audio_aio_fsync() { return -1; }
__attribute__((weak)) long audio_aio_open() { return -1; }
__attribute__((weak)) long audio_aio_post_event() { return -1; }
__attribute__((weak)) long audio_aio_release() { return -1; }
__attribute__((weak)) long bpf_ctx_narrow_access_offset() { return 0; }
__attribute__((weak)) long bpf_extension_prog_ops() { return 0; }
__attribute__((weak)) long bpf_extension_verifier_ops() { return 0; }
__attribute__((weak)) long bpf_image_ksym_add() { return 0; }
__attribute__((weak)) long bpf_iter_get_info() { return 0; }
__attribute__((weak)) long bpf_iter_link_attach() { return 0; }
__attribute__((weak)) long bpf_iter_new_fd() { return 0; }
__attribute__((weak)) long bpf_iter_prog_supported() { return 0; }
__attribute__((weak)) long bpf_iter_run_prog() { return 0; }
__attribute__((weak)) long bpf_jit_alloc_exec_page() { return 0; }
__attribute__((weak)) long bpf_ringbuf_discard_proto() { return 0; }
__attribute__((weak)) long bpf_ringbuf_output_proto() { return 0; }
__attribute__((weak)) long bpf_ringbuf_query_proto() { return 0; }
__attribute__((weak)) long bpf_ringbuf_reserve_proto() { return 0; }
__attribute__((weak)) long bpf_ringbuf_submit_proto() { return 0; }
__attribute__((weak)) long bpf_snprintf_btf_proto() { return 0; }
__attribute__((weak)) long bpf_struct_ops_map_ops() { return 0; }
__attribute__((weak)) long bpf_struct_ops_prog_ops() { return 0; }
__attribute__((weak)) long bpf_struct_ops_verifier_ops() { return 0; }
__attribute__((weak)) long bpf_trampoline_link_prog() { return 0; }
__attribute__((weak)) long bpf_trampoline_lookup() { return 0; }
__attribute__((weak)) long bpf_trampoline_put() { return 0; }
__attribute__((weak)) long bpf_trampoline_unlink_prog() { return 0; }
__attribute__((weak)) long btf_resolve_helper_id() { return 0; }
__attribute__((weak)) long btfm_slim_hw_init() { return -1; }
__attribute__((weak)) long cfg80211_vendor_cmd_reply() { return 0; }
__attribute__((weak)) long cg_dev_prog_ops() { return 0; }
__attribute__((weak)) long cg_dev_verifier_ops() { return 0; }
__attribute__((weak)) long cg_sockopt_prog_ops() { return 0; }
__attribute__((weak)) long cg_sockopt_verifier_ops() { return 0; }
__attribute__((weak)) long cg_sysctl_prog_ops() { return 0; }
__attribute__((weak)) long cg_sysctl_verifier_ops() { return 0; }
__attribute__((weak)) long cgroup_bpf_get() { return 0; }
__attribute__((weak)) long cgroup_bpf_inherit() { return 0; }
__attribute__((weak)) long cgroup_bpf_offline() { return 0; }
__attribute__((weak)) long cgroup_bpf_prog_attach() { return 0; }
__attribute__((weak)) long cgroup_bpf_prog_detach() { return 0; }
__attribute__((weak)) long cgroup_bpf_prog_query() { return 0; }
__attribute__((weak)) long dev_map_enqueue() { return 0; }
__attribute__((weak)) long dev_map_generic_redirect() { return 0; }
__attribute__((weak)) long dev_map_hash_ops() { return 0; }
__attribute__((weak)) long dev_map_ops() { return 0; }
__attribute__((weak)) long dev_xdp_enqueue() { return 0; }
__attribute__((weak)) long dwc3_pd_vbus_ctrl() { return 0; }
__attribute__((weak)) long enable_volume_ramp() { return 0; }
__attribute__((weak)) long fdt_check_header() { return 0; }
__attribute__((weak)) long fdt_first_property_offset() { return 0; }
__attribute__((weak)) long fdt_get_mem_rsv() { return 0; }
__attribute__((weak)) long fdt_get_name() { return 0; }
__attribute__((weak)) long fdt_getprop() { return 0; }
__attribute__((weak)) long fdt_getprop_by_offset() { return 0; }
__attribute__((weak)) long fdt_next_node() { return 0; }
__attribute__((weak)) long fdt_next_property_offset() { return 0; }
__attribute__((weak)) long fdt_node_check_compatible() { return 0; }
__attribute__((weak)) long fdt_parent_offset() { return 0; }
__attribute__((weak)) long fdt_path_offset() { return 0; }
__attribute__((weak)) long fdt_path_offset_namelen() { return 0; }
__attribute__((weak)) long fdt_setprop() { return 0; }
__attribute__((weak)) long find_vdd_level() { return 0; }
__attribute__((weak)) long flex_array_alloc() { return 0; }
__attribute__((weak)) long flex_array_free() { return 0; }
__attribute__((weak)) long flex_array_get() { return 0; }
__attribute__((weak)) long flex_array_get_ptr() { return 0; }
__attribute__((weak)) long flex_array_prealloc() { return 0; }
__attribute__((weak)) long flex_array_put() { return 0; }
__attribute__((weak)) long gcd() { return 0; }
__attribute__((weak)) long half_md4_transform() { return 0; }
__attribute__((weak)) long insert_eos_buf() { return 0; }
__attribute__((weak)) long int_sqrt() { return 0; }
__attribute__((weak)) long is_rate_valid() { return 0; }
__attribute__((weak)) long kgsl_add_event() { return -1; }
__attribute__((weak)) long kgsl_add_event_group() { return -1; }
__attribute__((weak)) long kgsl_add_fence_event() { return -1; }
__attribute__((weak)) long kgsl_cancel_events() { return -1; }
__attribute__((weak)) long kgsl_cancel_events_timestamp() { return -1; }
__attribute__((weak)) long kgsl_del_event_group() { return -1; }
__attribute__((weak)) long kgsl_drawobj_cmd_add_cmdlist() { return -1; }
__attribute__((weak)) long kgsl_drawobj_cmd_add_ibdesc() { return -1; }
__attribute__((weak)) long kgsl_drawobj_cmd_add_ibdesc_list() { return -1; }
__attribute__((weak)) long kgsl_drawobj_cmd_add_memlist() { return -1; }
__attribute__((weak)) long kgsl_drawobj_cmd_create() { return -1; }
__attribute__((weak)) long kgsl_drawobj_destroy() { return -1; }
__attribute__((weak)) long kgsl_drawobj_sparse_add_sparselist() { return -1; }
__attribute__((weak)) long kgsl_drawobj_sparse_create() { return -1; }
__attribute__((weak)) long kgsl_drawobj_sync_add_synclist() { return -1; }
__attribute__((weak)) long kgsl_drawobj_sync_add_syncpoints() { return -1; }
__attribute__((weak)) long kgsl_drawobj_sync_create() { return -1; }
__attribute__((weak)) long kgsl_drawobjs_cache_exit() { return -1; }
__attribute__((weak)) long kgsl_drawobjs_cache_init() { return -1; }
__attribute__((weak)) long kgsl_dump_syncpoints() { return -1; }
__attribute__((weak)) long kgsl_event_pending() { return -1; }
__attribute__((weak)) long kgsl_events_exit() { return -1; }
__attribute__((weak)) long kgsl_events_init() { return -1; }
__attribute__((weak)) long kgsl_flush_event_group() { return -1; }
__attribute__((weak)) long kgsl_ioctl_syncsource_create() { return -1; }
__attribute__((weak)) long kgsl_ioctl_syncsource_create_fence() { return -1; }
__attribute__((weak)) long kgsl_ioctl_syncsource_destroy() { return -1; }
__attribute__((weak)) long kgsl_ioctl_syncsource_signal_fence() { return -1; }
__attribute__((weak)) long kgsl_process_event_group() { return -1; }
__attribute__((weak)) long kgsl_process_event_groups() { return -1; }
__attribute__((weak)) long kgsl_sync_fence_async_wait() { return -1; }
__attribute__((weak)) long kgsl_sync_timeline_create() { return -1; }
__attribute__((weak)) long kgsl_sync_timeline_destroy() { return -1; }
__attribute__((weak)) long kgsl_syncsource_put() { return -1; }
__attribute__((weak)) long lcm_not_zero() { return 0; }
__attribute__((weak)) long md5_transform() { return 0; }
__attribute__((weak)) long mdss_dsi_debug_bus_init() { return 0; }
__attribute__((weak)) long mdss_dump_misr_data() { return 0; }
__attribute__((weak)) long mdss_mdp_hw_rev_debug_caps_init() { return 0; }
__attribute__((weak)) long module_add_driver() { return 0; }
__attribute__((weak)) long module_remove_driver() { return 0; }
__attribute__((weak)) long msm_ep_unconfig() { return 0; }
__attribute__((weak)) long msm_rpm_enter_sleep() { return 0; }
__attribute__((weak)) long msm_rpm_exit_sleep() { return 0; }
__attribute__((weak)) long msm_rpm_waiting_for_ack() { return 0; }
__attribute__((weak)) long net_rand_noise() { return 0; }
__attribute__((weak)) long of_msm_clock_register() { return 0; }
__attribute__((weak)) long parent_to_src_sel() { return 0; }
__attribute__((weak)) long q6asm_get_buf_index_from_token() { return 0; }
__attribute__((weak)) long q6asm_get_stream_id_from_token() { return 0; }
__attribute__((weak)) long q6asm_get_svc_version() { return 0; }
__attribute__((weak)) long rational_best_approximation() { return 0; }
__attribute__((weak)) long reciprocal_value() { return 0; }
__attribute__((weak)) long ringbuf_map_ops() { return 0; }
__attribute__((weak)) long swiotlb_alloc_coherent() { return 0; }
__attribute__((weak)) long swiotlb_dma_mapping_error() { return 0; }
__attribute__((weak)) long swiotlb_dma_supported() { return 0; }
__attribute__((weak)) long swiotlb_free_coherent() { return 0; }
__attribute__((weak)) long swiotlb_init() { return 0; }
__attribute__((weak)) long swiotlb_map_page() { return 0; }
__attribute__((weak)) long swiotlb_map_sg_attrs() { return 0; }
__attribute__((weak)) long swiotlb_sync_sg_for_cpu() { return 0; }
__attribute__((weak)) long swiotlb_sync_sg_for_device() { return 0; }
__attribute__((weak)) long swiotlb_sync_single_for_cpu() { return 0; }
__attribute__((weak)) long swiotlb_sync_single_for_device() { return 0; }
__attribute__((weak)) long swiotlb_unmap_page() { return 0; }
__attribute__((weak)) long swiotlb_unmap_sg_attrs() { return 0; }
__attribute__((weak)) long xdp_convert_zc_to_xdp_frame() { return 0; }
__attribute__((weak)) long xdp_warn() { return 0; }
