#ifndef _NET_FIB_NOTIFIER_H
#define _NET_FIB_NOTIFIER_H
enum fib_event_type {
\tFIB_EVENT_ENTRY_REPLACE = 0,
\tFIB_EVENT_ENTRY_ADD,
\tFIB_EVENT_ENTRY_DEL,
\tFIB_EVENT_RULE_ADD,
\tFIB_EVENT_RULE_DEL,
\tFIB_EVENT_NH_ADD,
\tFIB_EVENT_NH_DEL,
};
#endif
